#!/bin/bash
#Title........: KaliSetup.sh
#Description..: This is a tool that automate best tools installation.
#Author.......: Riccardo Papa
#Version......: 2.4
#Usage........: sudo ./KaliSetup.sh
# copyright(please read the license before sharing the code)
clear
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
echo """
			 ____________________________________________
			|			                     |
			|        The Code By :- Riccardo Papa        |
			|	 Telegram :- @PaposinDT              |
			|        Facebook :- https://cutt.us/kfNBv   |
			|        Youtube :-  https://cutt.us/fp49D   |
			|        Git Hub :- github.com/PaposinDT     |
            		|        Instagram:- https://cutt.us/2ZDRu   |
			|___________________________________________ | """
sleep 2
echo "					Version 1.1
                    	 	 Coded By Riccardo Papa
           	 	Want to support me?  paypal.me/ricky2006" \  #
#
echo 
sleep 1
echo "The installation speed depends on the signal strength."
echo 
sleep 1
echo "The installation process could take up to 7 minutes"
echo
sleep 1
echo "Installing..."
echo
sleep 1
apt-get update
apt-get upgrade -y
apt-get update
apt dist-upgrade -y
apt-get autoremove -y
apt-get update
apt-get upgrade -y
